### ISSUE TITLE
consider web thin client

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification#1]
There should probably be a web thin client which provides access to the HAPI server via a web interface, to aid with testing and provide access to data at meetings.  Chris wrote something like this for his prototypes, and this could be brought up to date with the spec.  

This also suffers a bit from fragmentation of server containers.  The server could be a Java/JSP web application, for example, using Autoplot's support for server-side graphics, but many data providers won't have a Java container.

**Comment by berniegsfc** [comment]
Isn't a thin web client html5/js?  Something like my [test client](https://cdaweb.sci.gsfc.nasa.gov/registry/hdp/hapi/client.html).  I don't plan to make my client pretty or useful (i.e., I don't plan to implement plotting) so your "client" will be more useful.  But someone could implement a useful html5/js client.  The title of this issue is misleading to me.  It sounds more like a server-autoplot client to me.

**Comment by jbfaden** [comment]
Yes, I think that was what I was imaging--and that looks great.  A HAPI server becomes something useful (and self-verifying) when it can look at the data it serves, and it would be nice if there was a bit of Javascript which could be added to any server that would allow it to be inspected.  

So is this something I could add to my server?  I'll have to poke around the code...

**Comment by jbfaden** [comment]
Perfect--I was able to easily copy client.html and client.js and point it to my server.  I'd suggest this code go on github as well...

**Comment by berniegsfc** [comment]
You might also need client.css but since I didn't bother making it very pretty, the css is minimal.  Note that the client will have trouble with servers that don't support CORS (Todd's server) and if it is hosted on https (like I have to use), it will also have trouble accessing hapi servers that are not https (Jon's server).  You'll see these problem in the browser's console.  The code cannot detect them and display an alert.

**Comment by jbfaden** [comment]
It works over http if I go to http://jfaden.net/~jbf/hapi/client/client.html but not http://sarahandjeremy.net/~jbf/hapi/client/client.html (which is really the same).  I think the JS code points to the HAPI server at "//jfaden.net/HapiServerDemo/hapi".

**Comment by berniegsfc** [comment]
Yes.  Since you are hosting it on a non-https site, the code will be able to call to non-https servers.  But since I can no longer put the client.html on a non-https site here at gsfc, it can't call non-https servers (mixed active content security violation).  I mentioned it because unless you have the browser console open, you may encounter the problem from my site and not see any error.  But on your site, you won't have that problem.   You might have the CORS problem if you add a hapi server that doesn't support cors.

**Comment by berniegsfc** [comment]
I've made a few improvements.  They're mostly for my and nand's hapi implementation since I can't call any of the others due to browser security (https, cors) issues.  If you're using a copy, you might want to re-download client.html/css/js.

**Comment by berniegsfc** [comment]
I didn't mean to close it.

**Comment by rweigel** [comment]
Closing because of lack of follow-up. I have added a project named "client-javascript" which references this  issue. https://github.com/hapi-server/client-javascript/blob/master/README.md
