### ISSUE TITLE
Document how to escape commas in parameter name

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#127]
We use a comma-separated list of parameters in the URL and need to state how commas in a parameter name should be escaped.

**Comment by jvandegriff** [comment]
There are no commas in all of CDAWeb parameter names (about 47,000 of them!)

In the spec:
No commas allowed in parameter names (comma is allowed in dataset names)
Clarify what "control characters" are: ASCII decimal 31 and below and 127

(need to update the spec in the area 3.6.1 where we talk about parameter names)

**Comment by jvandegriff** [comment]
after review and discussion, and after finding no commas in any of the 46,000+ parameter names in CDAWeb, we decided that:

**There shall not be any commas in parameter or dataset names.**

(The escaping or quoting within a request parameter is just too hard to get right so that the escaping survives multiple URL decodings, etc)

**Comment by rweigel** [comment]
Closed by 70944ab422965e8a25d4511e6d90449e1db6eb95
