### ISSUE TITLE
Way to ping server

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#135]
https://github.com/hapi-server/client-python/issues/45

> My main objective was trying to think of a simple way to do a sanity check (ring the door bell). i.e. make small request to see if I have the right address. this seemed like a convenient way that returns something small, but didn't exist in the client.

> It seems like it would be very useful if I wanted to add a compressed output format, and be able to check if it's available? I found hapi yesterday, so it is still new to me.

**Comment by jbfaden** [comment]
The "https://..../hapi" response should return a human-readable web page, and this is how I'll check to see if a server is really up.  (Also https://.../hapi/capabilities should be a short response, and can advertise the compressed output extension.)

**Comment by jbfaden** [comment]
Interesting, I thought it was required and I liked that it is.  I'd vote for it.  1) it's useful for introducing the human to the server, and 2) it's fun to see how people set it up.

**Comment by jvandegriff** [comment]
The `hapi/about` page is now required, so we could use that (but it's likely a static page)

An additional endpoint, like a `/ping` might also just get implemented as a static page.

A more purposeful page that does something active but quick would be better.
Maybe include some kind of dynamic content. Examples:
* last successfully served request
* last time data added

But Travis' test mechanism also does this, as do other ones, and any test should really be initiated outside the server.

So this needs more thought.

**Comment by jvandegriff** [comment]
Sandy: what about having the `about` response include a URL to call for testing purposes.

```
"sampleURL": "http://server.com/hap/info?id=MYBEST_DATA"
```

**Comment by jbfaden** [comment]
In the about request:

```
"testURLs": [ 
   { "URL":"http://server.com/hapi/data?id=MYBEST_DATA&...",
     "numberOfRecords": 1440 },
   { "URL":"http://server.com/hapi/info?id=MYBEST_DATA",
     "numberOfParameters": 23 },
   { "URL":"http://server.com/hapi/catalog",
     "numberOfDatasets": 1000 } 
]
```

**Comment by jvandegriff** [comment]
Other rejected options
-  list of URLs on the **required** landing page (most servers doing this already)
-  go through each dataset and look for ones with sample start and stop, and use the first one you find (some servers have no sample start and stop - CDAWeb, for example)
- a longer list of tests so that all internal aspects (different disks) of a server can be tested (but this is an internal testing task)


In the `/about` endpoint, what about specifying just the request parameters for a place where data should be expected? (You could allow more than one of these.)
```
  "dataTest": {
                "name": "MY_TEST_NAME",
                "queryParameters": {
                       "dataset": DATASET,
                       "start": "2023-01-01T12:00:00",
                       "stop": "2023-01-02T12:00:00",
                       "parameters": "a,b,c",
                        --OR--
                       "dataQuery": "dataset=DATASET_ID& start=2023-01-01T12:00:00&stop= 2023-01-02T12:00:00&parameters=a,b,c"
                   }
           # Server should return more than zero records as a result of this query.
           # So, for now, leave this off -- we can add it later if needed (it's an internal server task to test at this granularity)  
                 "expectedNumberOfRecords": 144 # schema requires this to be more than zero
   }
```

Pros/cons:
relative URLs, request parameter values broken out, both
Against relative URLs: harder to parse a URL than construct one; also security reasons - more full URLs allow more nefarious options, maybe; JSON schema validation is harder with full URL
Full URL allows easier human implementation of testing, but this should be uncommon.

**Comment by sandyfreelance** [comment]
Go with json parameters (no relative URL).  Change 'queryParameters' to just 'query'.

**Comment by rweigel** [comment]
Server should return more than zero records as a result of this query.

```json
  "dataTest": {
                "name": "MY_TEST_NAME",
                "query": {
                       "dataset": DATASET,
                       "start": "2023-01-01T12:00:00",
                       "stop": "2023-01-02T12:00:00",
                       "parameters": "a,b,c"
                   }
   }
```
