### ISSUE TITLE
clarify whether timestamps are for the start, middle or end of the interval

### ISSUE THREAD

**Issue by jvandegriff** [hapi-server/data-specification#15]
Currently, the HAPI spec says nothing about wether timestamps are for the start, middle, or end of the measurement interval.

Resolution:
For now, the spec will be neutral about the location of the time stamp.  The HAPI server just delivers the time stamps as they are in the data with no modifications other than formatting (making all time values ISO 8601 strings).

As a suggestion for the future (Version 2.0 or beyond) , this could be an optional attribute in the info header for the primary time column -- something to indicate the flavor of time stamp.
Maybe even an enum: (BEGIN, END, MIDDLE, OTHER, UNKNOWN)
{ "parameters": [ {"name": "Epoch", "type":"isotime", "timeStampLocation":"middle"} ] }

**Comment by jbfaden** [comment]
I believe they should be in the middle, or the "most representative" time tag.  CDFs were somewhat vague about this in the spec, and because of this ACE AC_K2_MFI is tagged at the beginning while most are tagged in the middle.  (The part of the spec that does say this indicates that they should be in the middle, see BIN_LOCATION for example.)  

When data cadence is clear this doesn't matter much, but when it is not, for example with the location of sampling energies, people almost always assume that the data is the center of the sampling.  There should really be no difference between times or energies, either way they are simply the independent variable, and for this reason when one number is used it should be the center.

**Comment by rweigel** [comment]
We have two options if we introduce this:

If timeStampLocation is given

(1) Cadence is required, or
(2) Cadence is kept as optional and validator gives a warning like "cadence is not required, but data cadence is not uniform so the given timeStampLocation is ambiguous" when it finds timeStampLocation and non-uniform cadence data from a sample request.

**Comment by jvandegriff** [comment]
It is not clear to me if we should just force all time stamp values to be the middle or "most representative" time. That would potentially force many providers to alter the time stamps in the data products they distribute through HAPI. But it does guarantee a more uniform interpretation of HAPI data, so we have to decide if this uniformity (timestamps are always in the middle) is worth adding a pretty serious requirement (many servers have to modify existing timestamps).

I suggest we make timeStampLocation optional, with it defaulting to "MIDDLE."

It is not clear to me why the cadence affects the timeStampLocation. Cadence is only a rough guide to the time between measurements, not an exact delta T between all values, so it seems independent.

**Comment by rweigel** [comment]
Cadence does not affect timeStampLocation.

But timeStampLocation alone could be ambiguous, and cadence _could_ be used to clarify.  We could instead add timeStampBinWidth.  Probably that would be better so that cadence does not have two meanings (nominal time between measurements or measurement/averaging interval if timeStampLocation is given).

If the time stamps are 01:00, 05:00, and 19:00 and you tell me timeStampLocation is "middle", what is the interval?  If the values correspond to hourly averages, and this is stated as the timeStampBinWidth, then there is no ambiguity.  One could say cadence = 1 hour, but then the meaning of cadence has changed.

**Comment by jvandegriff** [comment]
I see what you are saying now. I think having bin in the name might cause confusion since we have 'bins' mean something else, so maybe just timeStampWidth. Other options (in stream of consciousness mode) include: timeStampDuration, measurmentWidth, measurementDuration, accumulationTime or recordDuration.

I would be ok with having this kind of time width indicator. We need to run it by everyone else.

Note also that it only handles simple cases. There are more complex cases where the time width of the records is not constant, in which case you can't describe it with metadata and so I would also expect there to be one or more data columns (with good descriptions) to indicate the measurement window parameters, like an accumulation time (the denominator when going from counts to count rate), the measurement window (the total time window associated with a measurement, including dead time), etc.

**Comment by jvandegriff** [comment]
We will add an optional dataset description called "timeStampLocation" tha is an enum with these possible values: (BEGIN, CENTER, END, OTHER)

{ "parameters": [ {"name": "Epoch", "type":"isotime", "timeStampLocation":"CENTER"} ] }

If no "timeStampLocation" is provided, it defaults to "CENTER".

**Comment by jvandegriff** [comment]
Added optional parameter 'timeStampLocation' to dataset attributes: 2603550251fefee14d4f2192095981c35753a2f3

Added description about the new attribute to the Representation of Time:
9ee24e0e3f9c09243b0762664e13adbf446024b8

**Comment by rweigel** [comment]
The issue should have been closed (If you put, e.g., `closes #15` in the commit message, the issue will be closed on GitHub without the need to use the web interface.)
