### ISSUE TITLE
1404 default error message

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#35]
It is

1404: start time after stop time

It should be 

1404: start time equal to or after stop time

given spec says "time.max is exclusive (data at or beyond this time shall not be included in the response)."

One may try to get exactly one record by setting time.min=time.max in the request and then the current error would be confusing.

**Comment by jvandegriff** [comment]
I agree that the default message should be updated. The way the spec is written now, it is not valid to set time.min=time.max in a request. At best, this is ambiguous, since it asks for data to be included and excluded at the same time point.

I agree that changing the default error message helps clarify this. 

Also, the text where the spec describes the meaning of time.min and time.max should be changed to clarify that the requested time range must have non-zero duration (or we just explicitly state that time.max must be greater than and not equal to time.min.)

**Comment by rweigel** [comment]
99aac31a73d365c2d1edb2e2d6445858b4fc543b
