### ISSUE TITLE
Add requestURL to /info and /data responses?

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#45]
In principle, HAPI output is not meant to be an exchange format, so the answer could be no.

But if one is debugging a HAPI response written to a file, this sort of information is useful to see where the content of the response came from.

**Comment by jvandegriff** [comment]
There are security issues involved when including user input in the response. If the request was a valid one, it is hard to think of how anything nefarious could be stuffed in there, but nevertheless, it does provide a potential security hole.

Since it is for debugging, could you get by using a custom extension? Or have the server take an optional, custom debug flag that then causes an extra attribute to be included in the header?

**Comment by jvandegriff** [comment]
Debugging is outside the spec and everyone can add custom debugging info as needed.

**Comment by rweigel** [comment]
Besides debugging, there is a use for using this info to figure out where the contents of a stored file came from.  I agree that we can close; at present, clients that cache or write HAPI responses to disk add this to the header so it is a client-side issue.
