### ISSUE TITLE
String length is causing confusion

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#46]
The spec states that

"For type string and isotime; not allowed for others. The number of bytes or characters that contain the value, including the required null terminator character. Relevant only when data is streamed in binary format."

This is confusing if one counts the number of characters in the CSV and sees that the metadata says the string length is 1 plus what was counted.  The spec says it is correct, but it is not intuitive.

In the validations, I found many cases where the length of the time string in CSV was equal to the length in the metadata.  This would not be an error if the binary response replaced the last character of the time shown in the CSV response with a null, but I doubt that was planned and should not be allowed anyway.

**Comment by jvandegriff** [comment]
There are several issues to think through here. There are two lengths to consider - the "natural" length that matches the number of characters and the binary length that includes the null terminator. Also, for non-time strings, the null terminator indicates where the actual content of the string ends, since the length is the max length and some values could be shorter.

Here's one option:
The length attribute in string parameter descriptions represents the natural length of the contents of the string parameter - the number of visible (non-null) characters. This is not relevant for CSV or JSON, since delimiters tell you the boundaries. In the binary stream, a string value that is shorter than the length must be null-terminated to indicate where its valid content ends.


This means strings are only null terminated when needed. If they exactly fill the length - no null termination is needed.

**Comment by rweigel** [comment]
This needs discussion. All records in binary should have the same length and this was what I thought we agreed on.  Without records of the same length, we lose way too much in terms of performance for the binary read in Python and MATLAB and probably IDL and makes having binary almost pointless.  The server should pad strings out with nulls or spaces if they are less the natural length if they serve binary.

**Comment by jvandegriff** [comment]
I strongly agree that strings in binary should be the same length (not ragged). I'm suggesting that the only time a null terminator is needed is when the content of a string is less than than the fixed length (the number of bytes allotted to it in the header).

**Comment by toddking** [comment]
Hi all -

Sorry I missed the telecon. This option may have been discussed, but strings can be space padded to the max length. Trailing spaces are never meaningful and could safely be trimmed. 

-Todd-

**Comment by jvandegriff** [comment]
Change spec to this:

For type string and isotime; not allowed for others. The maximum number of bytes or characters that the string may contain, where unused bytes at the end are filled with null. Relevant only when data is streamed in binary format."

**Comment by rweigel** [comment]
c0aa8b9ca2f3c0d573a40019bdaf5c6a1edb1008
