### ISSUE TITLE
Order of parameters in request

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#69]
We need to address in the spec what the user can expect when they do

`?id=ID&parameters=Time,param1,param2`

vs

`?id=ID&parameters=Time,param2,param1`

or

`?id=ID&parameters=Time,param2,param1,param1`

I think we should say that the the user should expect that the order of the parameters is ignored as are duplicates; the order of the parameters in the output is uniquely specified by the header (or the info response with the same parameter list if no header is requested). This is implied by the spec, but we should be explicit.

We should also discuss if we ever want to allow a server to have the output column order specified by the user.

**Comment by jbfaden** [comment]
We have all agreed that Time is always sent, and one copy of each name mentioned is sent, and they are always sent in the order specified by info response.  All three examples you provide should have the same meaning.

**Comment by jvandegriff** [comment]
Re-opening based on discussion prior to 2.1 release.

The discussion ended up being about whether the data on the server was primary or the request was primary. This ticket claims we had previously agreed to the primacy of the data, which means  parameter order regardless of request order. Re-ordering the response based on the request gives the request the primacy.  Which is best for the HAPI specification long-term should be decided later in the interest of getting a 2.1 release out the door.

The case for not allowing re-ordering involves keeping servers simple (following our no bells and whistles principle). Also, re-ordering the parameters in the data also requires servers to reorder the parameters in the info response, which gives clients a seemingly overly active role in arranging the server's metadata.  But if you think about the metadata as just describing the stream content, then it is perhaps not as odd.

The suggested approach at this time is to take the least disruptive path to minimize code changes on servers (some servers do re-order parameters in the response and some don't). An easy option that is consistent with what was decided before (no-reordering) is to require servers to throw an error if the requested parameter order is different than the order listed in the info response.

In HAPI 2.1, HAPI status code 1400 could be used for the error, and then for HAPI 3.0, we could consider making a separate code , 1411 Bad request - parameters out of order.

If there is significant interest in supporting re-ordering, we could revisit that as a 3.0 feature request.

**Comment by jbfaden** [comment]
Here's the table which surveys nine servers.  I found it's about 50-50, and hard to justify either side.  I'll let Jon and Bob summarize what we came up with in our telecon this morning.  
[ParamOrderStudy.pdf](https://github.com/hapi-server/data-specification/files/3085627/ParamOrderStudy.pdf)

**Comment by aharonroberts** [comment]
I like having the order be what I put in, but can see that this is a complication for the server.  What I'll do in practice is have a client that takes care of things.

**Comment by rweigel** [comment]
In the spec, we should also recommend that the 1411 error message includes the correct URL. We also need to state that duplicates should be an error.

For the 2.1 release, I agree that it is best to make the least amount of change possible, which is an error message. In 2.0, the behavior was undefined.

We can re-visit for 3.0. It would be convenient for a user to be able to set the column order, but it seems odd to allow a user to how metadata would be ordered (which we would also need to allow for info requests if allowed for data requests).

**Comment by jbfaden** [comment]
Also, I think the more-server-implementations-than-client-implementations rule says that we should favor what's easier for the server even if it makes things more difficult for the client.  We already have more server implementations than client implementations. (I count nine servers, and maybe eight clients: Autoplot, MIDL, SPEDAS, Python, Matlab, IDL, JavaScript, wget).

**Comment by jvandegriff** [comment]
Summary of the discussion before today's telecon:

How to handle a user request for parameters that are not in the order listed in the HAPI metadata?
If you perceive of the metadata as the primary entity, then the order of the parameters should not be able to be changed by users.  Servers can be kept as simple as possible since dropping parameters from the return stream list is easier than rearranging them.  This also is in line with keeping the spec as simple as possible (no bells and whistles).

If you perceive of the request as the primary entity, then it is natural to expect the parameters in the response to line up with your request. This is more work for servers, especially when dealing with metadata, which will have to also be rearranged based on a user request.

The current implementations are split - some give the parameters and metadata in the user requested order, and some always give them in the HAPI info order. No matter what we decide, some servers will require a modification.

The proposed solution is that for 2.1.0, we require the request to have parameters in the same order as the metadata.  That way any valid request always has them parameters in the same order requested. This is a fairly easy change to make on the server side (checking the order). The error code to use would be a generic one:
    "1400": {"status":{"code": 1400, "message": "HAPI error 1400: user input error"}},
A later version of HAPI 
For the next version of HAPI, if someone wants to push for a change to allow reordering of parameters, we can entertain that discussion later.

**Comment by jvandegriff** [comment]
On the 2019-04-22 telecon, we emphasized that if out-of-order parameters are not allowed, duplicates should also be not allowed.

Also, we agreed to add an additional error code to describe exactly why the parameters were a problem. HEre's the new error code line for the spec document:

`"1411": {"status":{"code": 1411, "message": "HAPI error 1411: out of order or duplicate parameters"}},'''`

**Comment by rweigel** [comment]
Jon, when you edit the spec, put a link in the spec where this issue is discussed. Something like ... <sup>[Issue 69](https://github.com/hapi-server/data-specification/issues/69)</sup>.

The documentation should also include a statement that encourages a modified 1411 error that states the correct order.

**Comment by aharonroberts** [comment]
Sorry I missed yesterday, although I would not have had much to offer.

Cheers,
Aaron

**Comment by candeynasa** [comment]
Another reason for preserving order is to allow very simple servers that only return existing files, which was a goal early on.

**Comment by rweigel** [comment]
We concluded that for 2.1, order in URL is ignored and agreed to re-visit for 3.0. Documentation was updated in 3b0abacebd14b97d635757b8e40fea3d11931af6
