### ISSUE TITLE
Support for time and non-time varying parameters and JSON references

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/data-specification#71]
To better match CDF files and to support a new way which two ids can share the same y tags, we propose a new tag "constants" which would be a list like the "parameters", but would contain a tag "values" which would contain a comma-separated list of values.  Then parameters could then use these in their bins:

"constants": [
    {       "fill": null,
            "name": "Angles",
            "type": "double",
            "values": [15,45,75,105,135,165],
            "minValues": [0,30,60,90,120,150],
            "maxValues": [30,60,90,120,150,180],
            "units": "degrees"
        },
]
"parameters": [
        {
            "fill": null,
            "length": 24,
            "name": "Time",
            "type": "isotime",
            "units": "UTC"
        },
        {
 "bins": [{
                "name": "angle",
                "values": "Angles",
                "units": ""
            }],
            "fill": "-1.0E38",
            "name": "specBins",
            "size": [6],
            "type": "double",
            "units": ""
        }
    ]

**Comment by jvandegriff** [comment]
There are two types of constants.  The type described here is constant across each parameter and is most useful when multiple parameters share the same "bins" values. The other type is constant over time.

So I think this issue is misnamed and should instead should be called something like "allowing references and substitution in the header." 

It needs to be clear what JSON object is being substituted. We could consider using a simple substitution mechanism. Since the "bins" object is an array of objects, each JSON object in the "constants" list could be a drop in replacement for one object in a "bins" array. This makes is clear what content is being substituted.

I have not considered what this would do to header validation - it would definitely make it more complicated.  If we had a way to do pre-processing to expand all substitutions, the same schema could be used on the post-processed (i.e., expanded) header. But then the error messages might look confusing.

Here is a header with no substitution.

```json
{"HAPI": "2.0",
 "status": { "code": 1200, "message": "OK"},
 "startDate": "2016-01-01T00:00:00.000Z",
 "stopDate": "2016-01-31T24:00:00.000Z",
 "parameters": [
   { "name": "Time",
     "type": "isotime",
     "units": "UTC",
     "fill": null,
     "length": 24
   },
   { "name": "proton_spectrum",
     "type": "double",
     "size": [3],
     "units": "particles/(sec ster cm^2 keV)",
     "fill": "-1e31",
     "bins": [ {
         "name": "energy",
         "units": "keV",
         "centers": [ 15, 25, 35 ],
          } ]
    },
   { "name": "proton_spectrum_uncerts",
     "type": "double",
     "size": [3],
     "units": "particles/(sec ster cm^2 keV)",
     "fill": "-1e31",
     "bins": [ {
         "name": "energy",
         "units": "keV",
         "centers": [ 15, 25, 35 ],
          } ]
     }
 ]
}
```

Here is the same header with a "constants" array holding the one object that goes in the bins array.

```json
{"HAPI": "2.0",
 "status": { "code": 1200, "message": "OK"},
 "startDate": "2016-01-01T00:00:00.000Z",
 "stopDate": "2016-01-31T24:00:00.000Z",
 "constants" : 
   [
      {  "name": "proton_e_bins",
         "value": {  "name": "energy",
                           "units": "keV",
                           "centers": [ 15, 25, 35 ] }
       }
    ],
 "parameters": [
   { "name": "Time",
     "type": "isotime",
     "units": "UTC",
     "fill": null,
     "length": 24
   },
   { "name": "proton_spectrum",
     "type": "double",
     "size": [3],
     "units": "particles/(sec ster cm^2 keV)",
     "fill": "-1e31",
     "bins": [ { "constant": "proton_e_bins"  } ]
   },
   { "name": "proton_spectrum_uncerts",
     "type": "double",
     "size": [3],
     "units": "particles/(sec ster cm^2 keV)",
     "fill": "-1e31",
     "bins": [ { "constant": "proton_e_bins"  } ]
   }
 ]
}
```

**Comment by rweigel** [comment]
"constant" may not be the best choice of terms if there is not also a "varying" keyword.

In JSON schema, the use "$ref" instead of "constant" and put the references in an object named "definitions".

https://spacetelescope.github.io/understanding-json-schema/structuring.html

**Comment by rweigel** [comment]
Actually, if we don't use $ref, validation gets very complicated.

**Comment by jvandegriff** [comment]
It might be possible to use JSON references or pointers. Note sure yet if array dereferencing works...

Another option would be rethinking how we define parameters to also include items that only can be referenced in the header.

{"HAPI": "2.0",
 "status": { "code": 1200, "message": "OK"},
 "startDate": "2016-01-01T00:00:00.000Z",
 "stopDate": "2016-01-31T24:00:00.000Z",
 "definitions" : 
   {
      {  "proton_e_bins":  {  "name": "energy",
                                           "units": "keV",
                                           "centers": [ 15, 25, 35 ] }
       }
    },
 "parameters": [
   { "name": "Time",
     "type": "isotime",
     "units": "UTC",
     "fill": null,
     "length": 24
   },
   { "name": "proton_spectrum",
     "type": "double",
     "size": [3],
     "units": "particles/(sec ster cm^2 keV)",
     "fill": "-1e31",
     "bins": [ { "$ref": "#/definitions/proton_e_bins" } ]
   },
   { "name": "proton_spectrum_uncerts",
     "type": "double",
     "size": [3],
     "units": "particles/(sec ster cm^2 keV)",
     "fill": "-1e31",
     "bins": [ { "$ref": "#/parameters[1]/bins[0]" } ]    # this may not work?
   }
 ]
}

**Comment by jvandegriff** [comment]
Bobby is suggesting that we create a mechanism for using references in the header. Any time in the header that a value is needed, a reference could be used instead.  The main place this would be used is in defining the bins, where the use case is that the energy ranges for a spectrum might be repeated for multiple variables. For spectra, the data variable and the uncertainty variable will certainly have the same bins, for example. The other place this could be used is for time-varying bins. In this case, the reference points not to something in the header, but to a variable in the actual data.

This could be implemented by allowing a data value in the header to be replaced with a data reference. The reference could indicate wether it points to a header value or to a data column value.

**Comment by jvandegriff** [comment]
At the 2018-07-30 telecon, we tried to clarify options for various types of "reference variables" in the HAPI header and the HAPi data stream.

A reference is defined as replacing the value of a variable with a label that points to another value that should be substituted in at the place where the label is used. The only place in the header where a complex value is stored is the values for the bins object. Recall that the bins object has a specific layout whereby centers (a list of scalars, one for each bin) or ranges (list of min,max for each bin) or both can be provided.

There are 4 types of references:
**1. a header value is replaced by a reference to some other static value in the header**  
the use case is that the bins object may be the same for multiple parameters, so the actual centers and ranges are provided once in a special location and referenced within the actual parameter definitions  
**2. a header value is replaced by a reference to something in the data stream**  
The use case here is time varying values for the bins. What if the centers for the bins change? There could be parameters in the data to indicate bin centers as a function of time.  
**3. a value in the data stream is replaced by a constant value in the header.**  
This is the "non-time varying parameter" in the ticket title.
**4. a value present in one variable's definition is actually another variable in the data**  
The use case here is if the uncertainty values were referenced from within one parameter's definition, then you would just want to indicate which other parameter contained the uncertainty values.

One way proposed for this was to just have a generic concept of a variable, and that variable could be either the actual content or a reference to another variable with the actual content.  The objection for the bins was that the bins object has a specific schema that does not apply to a generic variable (it has centers and ranges), and so it would be strange to have optional attributes like centers and ranges on every variable just so they could actually be present when the variable contained values for a bins object.

There are significant implications in terms of increased complexity if references are added. If bin values cannot be obtained just from the header, then you have to ask for data to get actual bin values.  The header must be processed in two passes if it has references (either a pre-processing pass to inject in all substitutions as they are found, or a post-processing pass to look up all references -- this is safer in case a reference is mentioned before it is defined.)  The data model needed to absorb parameters that contain references to other parameters is also more complex. Finally, the ability to get a data stream without a header would be strange for some cases.  When there is a non-time varying parameter, the data will not refer to that parameter at all since it is just in the header. So it seems awkward to have the header and data be totally disconnected in this case. There was a suggestion that we always include the header to keep it connected to the data, and there were objections to this since it is convenient / expedient to be able to just get a stream of content.

What is needed are concrete examples of how these kinds of references could be implemented.  Then we can see if the gain in expressive capability is worrh the increase in complexity.

**Comment by jbfaden** [comment]
Here is an Autoplot URI for a dataset which has time-varying energies:
vap+cdaweb:ds=RBSPA_REL03_ECT-HOPE-PA-L3&filter=hope&id=FODO&timerange=2018-01-01

This may not be the best example, because it switches between a small number of modes each of which has constant frequencies.  For this we should also consider a method for identifying ids which are viewed together.  Another example would be an instrument which has a fast cadence mode and slow cadence mode.  If looking at an overview, you want to see both modes.  However if looking at the cadence metadata, one might expect these to be different.

**Comment by jbfaden** [comment]
http://jfaden.net/~jbf/autoplot/data/qds/timeVaryingDepend1.qds is a second case where the data has time-varying y-values.  This is fake data, where an enhancement near y=400 is visible for all times.

**Comment by jbfaden** [comment]
This shows an example of where the server must return y tags twice:
http://datashop.elasticbeanstalk.com/hapi/info?id=LEMMS_PHA_CHANNELS_FULL_TIME_RES

**Comment by jbfaden** [comment]
Here is an proposal for a new info format which has a "constants" area.  This is about 1/6 the size of the original.  Also in making this I noticed two things.  The name for the bins was always "energy", so I suspect that naming this thing is really not necessary, since it doesn't really identify anything.  Second I noticed that many of these bins were actually different, though I'd assumed they were the same.  Since they are repeated, it's easy to miss differences or similarities.

[files.zip](https://github.com/hapi-server/data-specification/files/2401610/files.zip)

**Comment by rweigel** [comment]
It is possible to put something here in the thread? Just truncate the JSON with "...". Will be easier to discuss.

**Comment by jbfaden** [comment]
Here's an abbreviated one where I took out the centers and ranges, and all but two of the constant blocks:

{
    "HAPI": "2.0",
    "cadence": "PT1M",
    "constants": [
        {
            "centers": "...",
            "name": "energyHPlus_BEST_T1",
            "ranges": "...",
            "units": "keV"
        },
        {
            "centers": "...",
            "name": "energyWPlus_BEST_T1",
            "ranges": "...",
            "units": "keV"
        },
        ...
    ],
    "creationDate": "2018-262T16:55:56.000Z",
    "description": "CHEMS PHA flux box intensities for many species at the highest time resolution",
    "parameters": [
        {
            "description": "time as UTC string to milliseconds",
            "fill": null,
            "length": 22,
            "name": "Epoch",
            "type": "isotime",
            "units": "UTC"
        },
        {
            "bins": {"name": "energyHPlus_BEST_T1"},
            "description": "HPlus_BEST_T1",
            "fill": "-1.0e38",
            "name": "HPlus_BEST_T1",
            "size": [32],
            "type": "double",
            "units": "particles/s/keV/cm^2/ster"
        },
        {
            "bins": {"name": "energyHPlus_BEST_T1"},
            "description": "HPlus_BEST_T2",
            "fill": "-1.0e38",
            "name": "HPlus_BEST_T2",
            "size": [32],
            "type": "double",
            "units": "particles/s/keV/cm^2/ster"
        },
        {
            "bins": {"name": "energyWPlus_BEST_T1"},
            "description": "WPlus_BEST_T1",
            "fill": "-1.0e38",
            "name": "WPlus_BEST_T1",
            "size": [24],
            "type": "double",
            "units": "particles/s/keV/cm^2/ster"
        },
        {
            "bins": {"name": "energyWPlus_BEST_T1"},
            "description": "WPlus_BEST_T2",
            "fill": "-1.0e38",
            "name": "WPlus_BEST_T2",
            "size": [24],
            "type": "double",
            "units": "particles/s/keV/cm^2/ster"
        },
        {
            "description": "degrees",
            "fill": "-1.0e38",
            "name": "PA_for_CHEMS_TALL",
            "type": "double",
            "units": "pitch angle for CHEMS data summed over all telescopes"
        }
    ],
    "resourceURL": "http://cassini-mimi.jhuapl.edu/MIDL/data/CPHAFULL0",
    "sampleStartDate": "2004-183T00:00:00.000Z",
    "sampleStopDate": "2004-184T00:00:00.000Z",
    "startDate": "2004-001T00:00:04.734Z",
    "status": {
        "code": 1200,
        "message": "OK"
    },
    "stopDate": "2017-258T10:31:10.425Z"
}

**Comment by rweigel** [comment]
Seems similar to shat was discussed earlier except this one does not address the later discussion about what is needed for JSON validation. See https://github.com/hapi-server/data-specification/issues/71#issuecomment-401888052.

**Comment by rweigel** [comment]
This needs clarification:

> 3. a value in the data stream is replaced by a constant value in the header. This is the "non-time varying parameter" in the ticket title.

Do we mean that the client should inspect the data stream and when it finds certain values, replace them with something in the header (as is essentially done with fill - if the client sees a -9999, it replaces it with a NaN, for example)?

**Comment by rweigel** [comment]
Note that the solution to this

> 2. a header value is replaced by a reference to something in the data stream. The use case here is time varying values for the bins. What if the centers for the bins change? There could be parameters in the data to indicate bin centers as a function of time.

is related to https://github.com/hapi-server/data-specification/issues/75#issuecomment-439390628

**Comment by jvandegriff** [comment]
For case 1, here is a way to handle $ref items in the header:

References are allowed, but they must be relative references, and the servers has the responsibility to make sure that there is enough information in the response to resolve the reference (filling in the content of the $ref if needed when, for instance, the definition portion of the header is not included in the response).

**Comment by rweigel** [comment]
For use case 2., we discussed allowing a value that is normally an array to also be a string with a parameter name prefixed with a `#`, in which case the array is meant to be time varying with values given by the referenced parameter. 

We also discussed the possibility of adding keywords for array parameters. The keywords are the original keywords postfixed by `Nominal`. The motivation is ...

```
    "parameters": [
        {
            "description": "time as UTC string to milliseconds",
            "fill": null,
            "length": 22,
            "name": "Epoch",
            "type": "isotime",
            "units": "UTC",
        },
        {
            "description": "proton_spectrum",
            "fill": "-1.0e38",
            "name": "proton_spectrum",
            "size": [32],
            "type": "double",
            "units": "particles/s/keV/cm^2/ster",

	    "bins": {
  
            // How to indicate a "typical" set of bins for exploratory purposes?

               "binsNominal": {
                  "centers": [1,2,3,4,5...32],
                  "ranges":  [   ]
                  "units": "keV"
               }
   
            --------- OR ----------

               "centersNominal": [1,2,3,4,5...32]
               "rangesNominal": [  [0,1.5], [1.5,2.5], [2.5,3.5], ... [30.5,32] ]

               "centers": "#ENERGY_CENTERS",
               "ranges": "#ENERGY_RANGES"   # must be a 2-D array in each record
                // Whatever you were expecting in the bins value (a center or a range), you now get one per record.

               // The following is not consistent with the statement "a value that is normally an array to also be a string with a parameter name prefixed with a `#`" because the format of ranges is [ [min,max], [min,max], ...] and would not be allowed.
               "ranges": ["#ENERGY_RANGE_MIN", "#ENERGY_RANGE_MAX"]
             }
        },
        {
            "name": "ENERGY_CENTERS",
            "size": [32],
            "type": "double",
            "units": "keV",
            "fill": "-1.0e38"
        },
        {
            "name": "ENERGY_RANGES",
            "size": [32,2],
            "type": "double",
            "units": "keV",
            "fill": "-1.0e38"
        },

```

**Comment by jvandegriff** [comment]
For now, it's best to leave out the nominal centers and ranges, since this is extra work for providers, and there is also the risk that clients would use the nominal values instead of looking up actual ones.

Since the nominal values are optional, clients need to deal with their absence anyway.

**Comment by jvandegriff** [comment]
Leaving # character as leading indicator for centers or ranges being a reference.

**Comment by jvandegriff** [comment]
This issue came up again as Fundamental Technologies staff are implementing a HAPI server for energetic particle data that has energy bins that change a few times during the mission.

**Comment by jvandegriff** [comment]
On the 2019-07-15 telecon, we devised a plan for dealing with this issue:

1. do some outreach to get ideas and buy-in from stakeholders; have a meeting with interested HAPI experts and some non-HAPI stakeholders for various data types (energetic particle and radio data seem to need this the most). Early August would be good for this. Potential people include: Eric Grimes, Bob Weigel, Jeremy Faden, and then also Baptiste Cecconi and Jerry Manweiler
1. hold a 2-day virtual hack-a-thon with HAPI experts to update the spec and try it out on a server / client pair; Jeremy, Bob, Jon, and Eric agreed to participate in this in mid or late August

There was a rehashing of the issue about wether to always include a header before the data. Although some people thought this was OK, the strong opinions were against always including the header before the data. 

The main argument for no header being that the data is not really usable without the header anyway, independent of any linkages or references added to the header.  So having it be optional can be friendlier for some computer-to-computer operations.

**Comment by rweigel** [comment]
Regarding the $ref notation

Python library: https://jsonref.readthedocs.io/en/latest/

Java: https://github.com/AndersDJohnson/jackson-json-reference

I use $refs in the HAPI schema: https://github.com/hapi-server/verifier-nodejs/blob/master/schemas/HAPI-data-access-schema-2.0.json

**Comment by rweigel** [comment]
More notes at https://github.com/hapi-server/data-specification/wiki/time-varying-bins-notes

**Comment by rweigel** [comment]
The result of this discussion is the proposals #82 and #83.
