### ISSUE TITLE
Need to address Unicode

### ISSUE THREAD

**Issue by rweigel** [hapi-server/data-specification#96]
Having `length` as the number of characters in a string parameter implies that only ASCII is allowed. This should be stated explicitly in the documentation. At present we point to a RFC for CSV, but that RFC allows non-ASCII.

I have had success with Unicode in the metadata (various libraries read it properly), but I have not tried Unicode in metadata when the header is included. That is, my code makes a request for metadata only and then makes a request for headerless CSV or binary. If there is Unicode in the header, then the content-type of the file must be set for clients to handle it properly.

**Comment by jbfaden** [comment]
This is a great point that we need to discuss some time.  I'd propose that we constrain strings in CSV to be UTF-8.  This is the trivial solution.  I'd propose then that strings in binary responses also be UTF-8 encoded, but clearly encoding requires care, as is error handling this when the binary stream is misformatted.  (The careful encoder would encode the string, then pop off any extra characters which don't fit.)

**Comment by jvandegriff** [comment]
need to address soon for 3.1

**Comment by berniegsfc** [comment]
Is this issue mainly concerned with csv and binary output?  I think json strings are utf-8 so they can support unicode characters without any special consideration.

**Comment by rweigel** [comment]
@berniegsfc - Yes, it is mainly concerned with csv and binary output. My understanding is also that when the HTTP header has `application/json`, the assumption is that it is UTF-8 encoded (https://stackoverflow.com/questions/9254891/what-does-content-type-application-json-charset-utf-8-really-mean). So for the case of catalog and info responses, I think everything should work.

For a CSV response with a header, it seems that we'll need to set `charset` to `UTF-8` if there is Unicode in the JSON part of the header. Same thing for binary. For a headerless CSV or binary response, one can use any `charset`.

Suppose that a dataset is a single parameter that is the letter `a`. Each record in the binary response will have a length of `lengthTime` + `1` bytes. 

If the single parameter was an arbitrary Unicode character and the server encoded the response as UTF-8, each record in the binary response will have a length of `lengthTime` + `n*length`, where `n` is at minimum `1` and at maximum `4`. (I've testing the UTF-8 encoder in the generic server and it always uses `n=4` with `null` padding.

**Comment by rweigel** [comment]
It seems that UTF-32 is the only fixed-length Unicode encoding scheme. So we should say binary HTTP response headers should indicate an 8-bit encoding or UTF-32.

**Comment by jvandegriff** [comment]
I think UTF-8 would be OK.  Strings are already variable length, and the server creators already have to scan the data to see what maximum length to pad everything to.  The only thing that changes with utf-8 is the interpretation of the bytes before the null terminator. There's not a known amount of actual characters in the utf-8 string, but that's true even with 8-bit strings in HAPI (since we allow shorter strings to be in there with zeros padding the end.)

So for the `length` value, it represents the number of bytes, and then based on the encoding, that will map to a range of values for the number of characters:

for an 8-bit string:  length=10 means a string of 0 to 9 characters (last byte reserved for null)

for a utf-8 string: length=10 also means a string of 0 to 9 characters; note that you could fit fewer 3-byte characters, but they might all be one-byte chars, so you need to reserve 10 chars for the string in case.

**Comment by rweigel** [comment]
I think Jeremy's point is that when you pad, you are no longer UTF-8.  From https://en.wikipedia.org/wiki/UTF-8#Overlong_encodings

> The standard specifies that the correct encoding of a code point uses only the minimum number of bytes required to hold the significant bits of the code point. Longer encodings are called overlong and are not valid UTF-8 representations of the code point.

See also https://en.wikipedia.org/wiki/UTF-8#Modified_UTF-8

**Comment by berniegsfc** [comment]
Overlong encoding involves padding with **leading** 0s.  But aren't we proposing **trailing** 0s (after the valid utf-8 encoding)?

**Comment by berniegsfc** [comment]
I guess trailing 0s (fill after the utf-8 string) are also a problem unless we use the modified utf-8.

**Comment by jvandegriff** [comment]
I was thinking we meant trailing zeros after all the utf-8 characters? Isn't that still valid utf-8?  This is the same as what we do for 8-bit strings.

**Comment by rweigel** [comment]
@jvandegriff - I don't think it would be valid. See the links I posted earlier.

**Comment by jbfaden** [comment]
I can't see why trailing zeros would be a problem.  The utf-8 string would be defined as the characters leading up to the zero terminator.  Whatever is after that shouldn't matter.  (I'm sure that's what C does as well when UTF-8 is handled.)

| String      | 10 Bytes |
| ----------- | ----------- |
| abc      | 97 98 99 0 0 0 0 0 0 0   |
| 天気   |229 164 169 230 176 151 0 0 0 0 |

**Comment by rweigel** [comment]
If we are going to zero pad, we might as well go with UTF-32. Then the strings are part of a standard (zero-padded UTF-8 is not).

UTF-8 strings can be 1-4 bytes, so we'd need to zero pad to 4 bytes in order to allow all possible code points. In this case, we may run into issues with libraries that don't handle zero-padded UTF-8 strings because they are not a part of the standard. So why not just use UTF-32?

**Comment by jbfaden** [comment]
I'm pretty sure zero-padded (trailing) UTF-8 is standard.  I think it's just UTF-8.  0 (U+0000) is NULL in both ASCII and in Unicode, right?  We could use UTF-32, which has the virtue that you can index each character randomly, but we have already decided that other parts should be UTF-8, so this seems more consistent to me.  Plus UTF-32 would be 4 times larger than the typical ASCII.  

Also, I'm not sure there's a good place to declare what format is used for encoding strings.  The Content-Type cannot be used to indicate that the strings are going to be UTF-32 or UTF-8, because this is the binary response.  We would have to come up with some way to communicate this, requiring more documentation.

**Comment by berniegsfc** [comment]
I think you need to use [mutf-8](https://en.wikipedia.org/wiki/UTF-8#Modified_UTF-8) to use a trailing null to signify the end of the string.

**Comment by rweigel** [comment]
@jbfaden

From https://en.wikipedia.org/wiki/UTF-8#Overlong_encodings

> The standard specifies that the correct encoding of a code point uses only the minimum number of bytes required to hold the significant bits of the code point. Longer encodings are called overlong and are not valid UTF-8 representations of the code point.

**Comment by jvandegriff** [comment]
Longer encodings refers to inflating individual characters.

I think there is still confusion about inflating/padding individual characters versus padding the end of the string of characters.  Padding individual characters so that they always have a certain width does indeed change the encoding, so you should not do it since it would not be valid utf-8 (or you should just use utf-32, like Bob mentioned). But padding a string at the end with zeros in space where there are no characters -- that does not change the encoding. In fact, how you terminate a string of encoded characters is actually not part of the encoding specification, as far as I can tell.  Since so many languages already deal with null padded strings, and we are doing that already with 8-bit strings, that having a null-terminated utf-8 string should pretty much be transparent, since that' what most languages are likely expecting.

From: Bob Weigel ***@***.***>
Reply-To: hapi-server/data-specification ***@***.***>
Date: Wednesday, July 28, 2021 at 9:09 AM
To: hapi-server/data-specification ***@***.***>
Cc: "Vandegriff, Jon" ***@***.***>, Mention ***@***.***>
Subject: [EXT] Re: [hapi-server/data-specification] Need to address Unicode (#96)

APL external email warning: Verify sender ***@***.*** before clicking links or attachments




@jbfaden<https://github.com/jbfaden>

From https://en.wikipedia.org/wiki/UTF-8#Overlong_encodings

The standard specifies that the correct encoding of a code point uses only the minimum number of bytes required to hold the significant bits of the code point. Longer encodings are called overlong and are not valid UTF-8 representations of the code point.

**Comment by jvandegriff** [comment]
It looks like mutf-8 that Bernie mentions uses a non-standard termination. Instead of using all zeros for a terminator, it uses a different byte sequence:  (copied from wikipedia) 11000000 10000000 (hexadecimal C0 80), instead of 00000000 (hexadecimal 00).

**Comment by jbfaden** [comment]
So this brings up an interesting point.  Is 97 98 99 0 0 0 0 0 0 0 a three-character string (abc) or is it abc followed by 7 nulls?  I think you would just have the convention, like C, that 0 terminates the string encoded within the HAPI stream.  It's not that the string has 10 characters, including the 7 nulls.

**Comment by rweigel** [comment]
Why use zero padding of UTF-8 to 32 bits instead of just using UTF-32?

In a binary reader, I would tell the library to read a chunk of 32 bits as UTF-32 and no extra step is needed. If I tell it to read a chunk of 32 bits with zero padding as UTF-8, will it just work or will an extra step be needed to strip off trailing zeros before passing the chunk of 1-4 bytes to a reader?

**Comment by rweigel** [comment]
Decode the letter `A`

```
>>> b"\x41".decode("utf-8") 
'A'
```

Decoding the letter `A` with null padding would require an extra step to remove the `\x00`:

```
>>> b"\x41\x00\x00\x00".decode("utf-8") 
'A\x00\x00\x00'
```

Using UTF-32 does not require an extra step:

```
>>> b"\x41\x00\x00\x00".decode("utf-32") 
'A'
```

**Comment by jbfaden** [comment]
I don't mean to pad each character, just the after the end of the string.  I think typically the text would be from the ASCII character set, so using UTF8 would mean strings could be 4 times shorter.  We could compromise and use UTF-16.  It looks like this would include Japanese and Chinese characters, and every character would be two bytes long, using English, Latin, or Chinese.

**Comment by jbfaden** [comment]
Note also we already have a null-termination rule, so "\x41\x00\x00\x00" is really just "A"

**Comment by berniegsfc** [comment]
I'm not sure why, but apparently it is important to be able to have the character with code point value zero **within** a utf-8 string.  That's the reason mutf-8 exists.

**Comment by jbfaden** [comment]
https://stackoverflow.com/questions/6907297/can-utf-8-contain-zero-byte shows why null is the only character that can contain the byte "0."  It seems to me that we should simply disallow null within the string and use null to terminate the string.

**Comment by jbfaden** [comment]
We resolved that null-terminated UTF-8 should be used.  Bob will come up with some tests for clients to test against.

**Comment by rweigel** [comment]
Another issue that I thought of while working on setting up a server to test with is if there is a comma in a string, it is escaped in the csv response. Is it removed in the binary response? Is it accounted for in `length`?

**Comment by jbfaden** [comment]
I believe that the only way to include a comma in a CSV response would be to quote the string.  The quotes are part of the syntax of the CSV, and are not part of the string itself.  To text this, I would make a spreadsheet in Google docs and export the sheet as CSV.

**Comment by rweigel** [comment]
@jbfaden - correct, it must be escaped. Is the escape character removed in the binary response? I would think so, but we should be explicit.

**Comment by jbfaden** [comment]
Yes, I agree it shouldn't need to have the escape character (or quotes).

**Comment by jbfaden** [comment]
(Maybe by escaped you mean quoted.  When you mentioned escaped I was thinking something like \, . )

**Comment by jvandegriff** [comment]
For end-of-string indicators, here is what we decided:

We will use a null character to indicate the content of a string is ended.  Since unicode uses null as a valid character, this means HAPI clients will need special processing to get string values out of data, but this is not a huge burden since they need some kind of processing anyway.

(This is needed since our strings are fixed length and need to be padded after the content ends.  So special processing is always needed to get out just the actual string content and ignore the padding bytes at the end of the string. All padding bytes should be zeros and not spaces.)

Options for `size` of strings:
1. number of bytes in binary stream for that parameter
2. number of characters

The first option seems to be the best - it answers how many bytes the reader should pull from the stream.

We need to experiment with Matlab and Python and Java to see how this will work in practice.

If a string completely fills  the bytes, with no terminator on the end, that is OK - the content is then just the bytes that are there. Unicode characters should not get truncated at the end - a partial unicode character is a bug in the server code - you should terminate the string rather than have it get arbitrarily truncated.

**Comment by jvandegriff** [comment]
If a server finds that the `length` it allocated is not big enough (which is really a server error!), then it should not send a truncated unicode character (i.e., don't just chop the unicode by an arbitrary number of bytes).

The server has options at this point:
1. ignore this advice, send a bad unicode char and hope the client has good error handling
2. terminate the stream (nuclear option) to prevent clients from accidentally using bad data; then hopefully the server owner finds out and fixes it quickly
3. if detected early enough, set an error code in the HAPI response

When server owners go back and fix the length (to increase it to handle longer string), it is up to server owners whether or not to make a new dataset or just change it in place.

For self defense purposes, clients should be resilient against partial unicode chars being sent by unruly servers.  

This is probably not a security issue. Hopefully the binary reader won't walk off the end - the binary reader is supposed to only read `length` bytes, but this is often hidden in a low-level routine, so client capability for handling truncated unicode is likely variable.

**Comment by jvandegriff** [comment]
There are a few updates to the above text, noted in bold. The biggest is changing a "should" to a "shall."

If a server finds that the `length` it allocated is not big enough (which is really a server error!), then it **shall** not send a truncated unicode character (i.e., don't just chop the unicode by an arbitrary number of bytes).

The server has options at this point:
1. ignore this advice, send a bad unicode char and hope the client has good error handling **(this is not compliant with the spec)**
2. terminate the stream (nuclear option) to prevent clients from accidentally using bad data; then hopefully the server owner finds out and fixes it quickly **(technically compliant but still disruptive)**
3. if detected early enough, set an error code in the HAPI response **(ideal but hard since it requires looking at all the data before sending it out to check string lengths)**

When server owners go back and fix the length (to increase it to handle longer string), it is up to server owners whether or not to make a new dataset or just change it in place.

For self defense purposes, clients should be resilient against partial unicode chars being sent by unruly servers.  

This is probably not a security issue. Hopefully the binary reader won't walk off the end - the binary reader is supposed to only read `length` bytes, but this is often hidden in a low-level routine, so client capability for handling truncated unicode is likely variable.

**Comment by rweigel** [comment]
The Python and MATLAB clients will allocate memory for a string parameter with Unicode and null padding. For example, in the following the array element is `α` and then two nulls. When the value of `a[0]` is printed, only the `α` is displayed even though space is allocated (the `U3` means the parameter takes 3 Unicode bytes)

```
a = np.array(["\u03b1\x00\x00"]) # array(['α'], dtype='<U3')
a[0]
'α'
```

As a result, we will update the documentation to state that for a string parameter, `length` means the max number of bytes and if the parameter has fewer than `length` bytes, it should be null padded.
